### ISSUE TITLE
I can't open Artisan anymore

### ISSUE THREAD

**Issue by cekefun** [PunishXIV/Artisan#62]
I updated my plugins (probably also Artisan) while working on a crafting list.
It caused my game to crash.

Now I can't open Artisan anymore. Here's what I've tried:

* Restarting the game
* Turning off the addon (causes an unload error so I can't turn it on again)
* Uninstalling and re-installing the addon

If you need any more information, feel free to reach out.

**Comment by Taurenkey** [comment]
This should be fixed in the latest update.

**Comment by cekefun** [comment]
While i can now disable and enable it, I still can't open it 😭
